### Creates a new patient entity
POST http://localhost:4000/api/v1/patients
Content-Type: application/json

{
  "firstName": "Harim",
  "lastName": "Zermeno",
  "gender": "MALE",
  "preferredLanguage": "en",

  "email": "harim2@example.com",
  "phoneNumber": "+15559234567",

  "addressLine1": "123 Main St",
  "addressLine2": "Apt 4B",
  "city": "Springfield",
  "state": "CA",
  "postalCode": "90001",
  "country": "USA",

  "dateOfBirth": "1995-09-02",
  "registeredDate": "2024-11-28",

  "emergencyContactName": "Jane Doe",
  "emergencyContactPhone": "+15559876543",
  "emergencyContactRelation": "Spouse"
}

###