### Updates an existing patient entity
PUT http://localhost:4000/api/v1/patients/0464ee0e-2116-4f23-a4dd-a8e3fd490b58
Content-Type: application/json

{
  "firstName": "John UPDATED",
  "lastName": "Doe UPDATED",
  "gender": "MALE",
  "preferredLanguage": "en",

  "phoneNumber": "+15551234567",

  "addressLine1": "123 Main St",
  "addressLine2": "Apt 4B",
  "city": "UPDATED ADDRESS",
  "state": "CA",
  "postalCode": "90001",
  "country": "USA",

  "dateOfBirth": "1995-09-02",

  "emergencyContactName": "Jane Doe",
  "emergencyContactPhone": "+15559876543",
  "emergencyContactRelation": "Spouse"
}
###